### ISSUE TITLE
file missing in github?

### ISSUE THREAD

**Issue by rogerguess** [marcmerlin/FastLED_NeoMatrix#1]
https://github.com/marcmerlin/FastLED_NeoMatrix/blob/9c6fab9f548c18777a1fab2be2faf35264e0a5fa/examples/espgifread/espgifread.ino#L9

thanks

**Comment by marcmerlin** [comment]
So, this code was written for ESP8266 since it uses its API to read directly from flash.
This is where that file comes from.
What chip are you running on?

**Comment by marcmerlin** [comment]
I can still help if need be, but I added an ifdef to address your concern

**Comment by dallen98** [comment]
espgifread doesnt compile on esp32 "user_interface.h: No such file or directory" although it compiles when esp8266 is selected, i,m using arduino ide 1.8.12, any chance of a fix or seperate sketch ? thanks

**Comment by marcmerlin** [comment]
@dallen98 you are correct, I messed this up, this code isn't compatible with ESP32 (the file interface is actually incompatible between 8266 and 32).

But see the readme in 
https://github.com/marcmerlin/FastLED_NeoMatrix/tree/master/examples/espgifread
this code is obsolete, I have a much better version up which supports teensy, ESP8266 and ESP32 with sdcard, spiffs, and fatfs

So, I'm going to keep this closed as wontfix, sorry.
But trust me, the new code is much better :)

**Comment by dallen98** [comment]
ok thanks, what i,m trying to do is create a 180 high x 360 wide neomatrix, i want a 16mm pixel pitch nb 60 leds per meter ws2812b, i,m helped in this endeavour by yves bazin latest code that outputs 810 leds on each pin, i have 80 pins so 80 x 810 leds =64800 leds, the next question for me is how to get an moving image onto this 180x360 matrix, i have looked at xlights, jinx, and the new glediator3 and for an assortment of reasons they dont seem to work on such a large matrix, i require something like 25-30fps so i,m thinking animated giffs on spiffs, the esp32 will be attached to a raspberry pi via usb cable, i am able to remote desktop into this pi to change the giffs, any guidance would be much appreciated thanks dave

**Comment by marcmerlin** [comment]
I assume you're already on the fastled reddit. If not, please go there for general help and advise.
As far as my lib is concerned, it would work with 64K pixels, although I have not tested that due to the price of such an array.
One thing to keep in mind, the framebuffer only will be 192KB and that isn't going to fit well on an ESP32, especially you're adding a 2nd array for the GIF. This should be possible with PSRAM but you're definitely going to be pushing the limits of the ESP32.
See these links:
- http://marc.merlins.org/perso/arduino/post_2020-01-14_LCA-2020-Talk_-ESP32-Memory-Management_-Neopixels-and-RGBPanels.html => 160KB is the most you can get in a block without PSRAM
- http://marc.merlins.org/perso/arduino/post_2019-05-26_FastLED_SPITFT_GFX-on-top-of-Framebuffer_GFX-for-SPI-TFTs-like-SSD1331-or-ILI9341.html => 320x240 supported by underlying lib
- http://marc.merlins.org/perso/arduino/post_2020-01-01_Running-FastLED_-Adafruit_GFX_-and-LEDMatrix-code-on-High-Resolution-RGBPanels-with-a-Raspberry-Pi.html => I use rPi
- http://marc.merlins.org/perso/arduino/post_2020-01-24_Running-Arduino-code-with-2D-FastLED_-Adafruit_GFX_-and-LEDMatrix-displays-on-Linux.html  => running code on linux/rPi
- http://marc.merlins.org/perso/arduino/post_2020-03-13_RGB-Panels_-from-192x80_-to-384x192_-to-384x256-and-maybe-not-much-beyond.html => all the code works on higher res, but I haven't tested on ESP32 due to lack of RAM for rgbpanels. 

If you need further help, unless it's with my library code directly, please use https://www.reddit.com/r/FastLED/   and https://github.com/marcmerlin/AnimatedGifs

**Comment by dallen98** [comment]
4mb circular ring buffer on psram is discussed on this video https://youtu.be/6BK4fzRaFGY?t=555  not sure if its relevant ?

Would it be true to say that anything i can get on the ili9341 tft 240x320 pixels would automatically work via fastled onto a ws2812b matrix of the same dimensions ?  and do i lose or gain by having the gifs on sd card over spiffs ?

**Comment by marcmerlin** [comment]
If you need further help, unless it's with my library code directly, please use https://www.reddit.com/r/FastLED/
feel free to give me the link to the post

**Comment by dallen98** [comment]
thanks

**Comment by marcmerlin** [comment]
sorry, I missed the 2nd part of your message. I do try to keep the github issues for actual issues.  

Basically, PSRAM is 4MB of RAM where you'll have to stick your big framebuffer as it will not fit in regular RAM.
Yes, anything you can get working on 320x240 TFT should work with FastLED if you manage to get that many pixels working (and the price will be horrendous, did you calculate that?), and 320x240 does no fit in regular ESP32 RAM, you have to use PSRAM when you define the buffer with malloc in neomatrix_config.h
Using sdcard or spiffs/fatfs does not impact memory use.

But before you go further, 16x16 is around $20 or so?  320x240 is 300 times bigger, so it'll cost you $6000 and that's not counting wiring and the 3000 Amps of 5V power supplies you'll need (10A for each 16x16)

That's what I use rgbpanels instead for those resolutions

**Comment by marcmerlin** [comment]
and all of the above, really, should have been in the fastled reddit, as it's useful to others, and no one will see it here

**Comment by dallen98** [comment]
On a full build I would use ws2815 12 volts which I calculate to be 6648 USD from here... https://www.aliexpress.com/store/group/WS2815/5630034_517204985.html?spm=a2g0o.detail.100008.7.667c17f15Nyb5S

i need the 16mm pitch (60 leds per meter) because its a outdoor billboard 20 feet wide x 10 feet high

**Comment by dallen98** [comment]
article on using mjpeg 30fps https://www.instructables.com/Play-Video-With-ESP32/

**Comment by marcmerlin** [comment]
this would be great to post on the fastled reddit, if you do build this, you'll have the biggest matrix on record and 1500Amps of 12V power supplies will also be a record (actually it should be 6000 amps if you do full power full white on all the pixels)
