### ISSUE TITLE
Not issue 

### ISSUE THREAD

**Issue by pepster01** [marcmerlin/FastLED_NeoMatrix#11]
Is possible to change the date pin as is not listed in the config.h , the default is pin 6 for the data pin,
is the a line I need to edit?
Thanks x the help

**Comment by marcmerlin** [comment]
it depends on what example you used, but it should be easy to find regardless and I assume you found it :)

**Comment by pepster01** [comment]
I'm using the espgifread example, still can't find it :(

**Comment by marcmerlin** [comment]
Ok, that example is very deprecated in favor of the more complete (and also more complex) https://github.com/marcmerlin/AnimatedGIFs
The pin number would be here
https://github.com/marcmerlin/FastLED_NeoMatrix/blob/40fb822377497a7be8e1103be344104870ff0878/examples/espgifread/espgifread.ino#L148
because that example uses PORTA, there is no pin number since they are hardcoded, but you can replace this with the appropriate FastLED init for your matrix.

**Comment by marcmerlin** [comment]
All my newer code uses neomatrix_config.h in that case there is a define MATRIXPIN and it's used here
https://github.com/marcmerlin/AnimatedGIFs/blob/179a2d6593f073beb29cbaf9bffe06a3f91b95ab/neomatrix_config.h#L1009

**Comment by pepster01** [comment]
That would explain a lots, 
Thanks, appreciate for the help.
