### ISSUE TITLE
Better Documentation of using the Demos

### ISSUE THREAD

**Issue by tonesto7** [marcmerlin/FastLED_NeoMatrix#3]
I have basically the exact same setup as you do for the NeoMatrix_LedMatrix (3 - 32x8 Matrix's) and it works great for that demo.  I like to get all of the NeoMatrix_LedMatrix_IR effects setup but it constantly tells me to create a config but I can find any notes on where to define the config. 

There is a neomatrix_config.h and nfldefines.h.  As a software dev myself I feel i've spent way more time on this then I should have too to understand it.

I appreciate all your efforts and posts but you don't explain how to utilize this massive new library.
If you could kindly offer some assistance I would appreciate it.

**Comment by marcmerlin** [comment]
Hi,
Sorry that I somehow managed to miss your issue until now.
The good news is that I cleaned up neomatrix_config.h a fair amount, so that it's easier to read/configure.

nfldefines.h you should not need unless you use my massive demo, but when you're ready for it, nfldefines shouldn't be a big deal to tweak as you need it.
Either way, you should start with https://github.com/marcmerlin/FastLED_NeoMatrix_SmartMatrix_LEDMatrix_GFX_Demos
and a simple example like https://github.com/marcmerlin/FastLED_NeoMatrix_SmartMatrix_LEDMatrix_GFX_Demos/tree/master/GFX/fontzoom

Once you got that working, add LEDMatrix (which sadly uses its on mapping function), and try to run
https://github.com/marcmerlin/FastLED_NeoMatrix_SmartMatrix_LEDMatrix_GFX_Demos/tree/master/LEDMatrix/LEDSprites-Pacman
or
https://github.com/marcmerlin/FastLED_NeoMatrix_SmartMatrix_LEDMatrix_GFX_Demos/tree/master/LEDMatrix/Table_Mark_Estes

Hopefully it helps. I'll close this given how long it took me to reply, I'm not sure if it's too late (sorry if it is), but feel free to reply if you need more help.

**Comment by tonesto7** [comment]
Thanks for replying I will definitely give it a try when I get some time. Thanks again for all your efforts
